<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Version>$(VersionPrefix).$(VersionSuffix)</Version>
    <PackageOutputPath>$(SolutionDir)Packages\</PackageOutputPath>
    <TargetFrameworks>net48</TargetFrameworks>
    <IncludeSymbols Condition="'$(Configuration)'=='Debug'">true</IncludeSymbols>
    <SymbolPackageFormat Condition="'$(Configuration)'=='Debug'">snupkg</SymbolPackageFormat>
    <IncludeSymbols Condition="'$(Configuration)'!='Debug'">false</IncludeSymbols>
    <AssemblyTitle>EFCachingProvider.Tests</AssemblyTitle>
    <Company>Microsoft</Company>
    <Product>EFCachingProvider.Tests</Product>
    <Copyright>Copyright (c) Microsoft Corporation</Copyright>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <Import Project="..\Common.targets" />
  <ItemGroup>
    <ProjectReference Include="..\EFCachingProvider\EFCachingProvider.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>